export enum StatusDemanda {
  ABERTA = 'ABERTA', // ABERTA PELO CLIENTE
  EM_ANDAMENTO = 'EM_ANDAMENTO', // ACEITA PELO CLIENTE
  CONCLUIDA = 'CONCLUIDA', // CONCLUIDA PELO PRESTADOR
  CANCELADA = 'CANCELADA', // CANCELADA PELO CLIENTE
}

export enum PrioridadeDemanda {
  BAIXA = 'BAIXA',
  MEDIA = 'MEDIA',
  ALTA = 'ALTA',
}

export enum StatusProposta {
    PENDENTE = 'PENDENTE', //ENVIADA PELO PRESTADOR
    ACEITA = 'ACEITA',        // ACEITA PELO CLIENTE
    RECUSADA = 'RECUSADA',        // RECUSADA PELO CLIENTE
    CANCELADA = 'CANCELADA'      //CANCELADA PELO PRESTADOR
}