version: "3.9"

services:
  db:
    image: postgres:15
    container_name: market_db
    environment:
      POSTGRES_DB: market_sv
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: "./market_service_backend"
      dockerfile: Dockerfile
    container_name: market_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: pg
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/market_sv
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "1234"
    depends_on:
      - db

  frontend:
    build:
      context: "./market_service_frontend"
      dockerfile: Dockerfile
    container_name: market_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
