services:
  db-market:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      - POSTGRES_DB=market_sv
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d market_sv"]
      interval: 5s
      timeout: 5s
      retries: 5
  app-backend:
    build: 
      context: ./market_service_backend  
      dockerfile: Dockerfile            
    container_name: market_service_app
    ports:
      - "8080:8080"
    depends_on:
      db-market:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-market:5432/market_sv
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_PROFILES_ACTIVE=pg
     # - SPRING_PROFILES_ACTIVE=pg-docker  # usar pg-docker